# container for Docker: MySQL
# ref: https://hub.docker.com/_/mysql
# Use root/example as user/password credentials
version: '3.1'

services:
  mysqldb:
    image: mysql
    container_name: some-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./docker_conf:/etc/mysql/conf.d
      - ./docker_vol:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

